COUNTRY_CODES = {
    # A
    "afghanistan": ("en", "AF"),
    "albania": ("en", "AL"),
    "algeria": ("en", "DZ"),
    "andorra": ("en", "AD"),
    "angola": ("en", "AO"),
    "antigua and barbuda": ("en", "AG"),
    "argentina": ("en", "AR"),
    "armenia": ("en", "AM"),
    "australia": ("en", "AU"),
    "austria": ("en", "AT"),
    "azerbaijan": ("en", "AZ"),
    # B
    "bahamas": ("en", "BS"),
    "bahrain": ("en", "BH"),
    "bangladesh": ("en", "BD"),
    "barbados": ("en", "BB"),
    "belarus": ("en", "BY"),
    "belgium": ("en", "BE"),
    "belize": ("en", "BZ"),
    "benin": ("en", "BJ"),
    "bhutan": ("en", "BT"),
    "bolivia": ("en", "BO"),
    "bosnia and herzegovina": ("en", "BA"),
    "botswana": ("en", "BW"),
    "brazil": ("en", "BR"),
    "brunei": ("en", "BN"),
    "bulgaria": ("en", "BG"),
    "burkina faso": ("en", "BF"),
    "burundi": ("en", "BI"),
    # C
    "cabo verde": ("en", "CV"),
    "cambodia": ("en", "KH"),
    "cameroon": ("en", "CM"),
    "canada": ("en", "CA"),
    "central african republic": ("en", "CF"),
    "chad": ("en", "TD"),
    "chile": ("en", "CL"),
    "china": ("en", "CN"),
    "colombia": ("en", "CO"),
    "comoros": ("en", "KM"),
    "congo": ("en", "CG"),
    "democratic republic of congo": ("en", "CD"),
    "costa rica": ("en", "CR"),
    "croatia": ("en", "HR"),
    "cuba": ("en", "CU"),
    "cyprus": ("en", "CY"),
    "czech republic": ("en", "CZ"),
    "czechia": ("en", "CZ"),
    # D
    "denmark": ("en", "DK"),
    "djibouti": ("en", "DJ"),
    "dominica": ("en", "DM"),
    "dominican republic": ("en", "DO"),
    # E
    "ecuador": ("en", "EC"),
    "egypt": ("en", "EG"),
    "el salvador": ("en", "SV"),
    "equatorial guinea": ("en", "GQ"),
    "eritrea": ("en", "ER"),
    "estonia": ("en", "EE"),
    "eswatini": ("en", "SZ"),
    "ethiopia": ("en", "ET"),
    # F
    "fiji": ("en", "FJ"),
    "finland": ("en", "FI"),
    "france": ("en", "FR"),
    # G
    "gabon": ("en", "GA"),
    "gambia": ("en", "GM"),
    "georgia": ("en", "GE"),
    "germany": ("en", "DE"),
    "ghana": ("en", "GH"),
    "greece": ("en", "GR"),
    "grenada": ("en", "GD"),
    "guatemala": ("en", "GT"),
    "guinea": ("en", "GN"),
    "guinea-bissau": ("en", "GW"),
    "guyana": ("en", "GY"),
    # H
    "haiti": ("en", "HT"),
    "honduras": ("en", "HN"),
    "hungary": ("en", "HU"),
    # I
    "iceland": ("en", "IS"),
    "india": ("en", "IN"),
    "indonesia": ("en", "ID"),
    "iran": ("en", "IR"),
    "iraq": ("en", "IQ"),
    "ireland": ("en", "IE"),
    "israel": ("en", "IL"),
    "italy": ("en", "IT"),
    "ivory coast": ("en", "CI"),
    # J
    "jamaica": ("en", "JM"),
    "japan": ("en", "JP"),
    "jordan": ("en", "JO"),
    # K
    "kazakhstan": ("en", "KZ"),
    "kenya": ("en", "KE"),
    "kiribati": ("en", "KI"),
    "kuwait": ("en", "KW"),
    "kyrgyzstan": ("en", "KG"),
    # L
    "laos": ("en", "LA"),
    "latvia": ("en", "LV"),
    "lebanon": ("en", "LB"),
    "lesotho": ("en", "LS"),
    "liberia": ("en", "LR"),
    "libya": ("en", "LY"),
    "liechtenstein": ("en", "LI"),
    "lithuania": ("en", "LT"),
    "luxembourg": ("en", "LU"),
    # M
    "madagascar": ("en", "MG"),
    "malawi": ("en", "MW"),
    "malaysia": ("en", "MY"),
    "maldives": ("en", "MV"),
    "mali": ("en", "ML"),
    "malta": ("en", "MT"),
    "marshall islands": ("en", "MH"),
    "mauritania": ("en", "MR"),
    "mauritius": ("en", "MU"),
    "mexico": ("en", "MX"),
    "micronesia": ("en", "FM"),
    "moldova": ("en", "MD"),
    "monaco": ("en", "MC"),
    "mongolia": ("en", "MN"),
    "montenegro": ("en", "ME"),
    "morocco": ("en", "MA"),
    "mozambique": ("en", "MZ"),
    "myanmar": ("en", "MM"),
    # N
    "namibia": ("en", "NA"),
    "nauru": ("en", "NR"),
    "nepal": ("en", "NP"),
    "netherlands": ("en", "NL"),
    "new zealand": ("en", "NZ"),
    "nicaragua": ("en", "NI"),
    "niger": ("en", "NE"),
    "nigeria": ("en", "NG"),
    "north korea": ("en", "KP"),
    "north macedonia": ("en", "MK"),
    "norway": ("en", "NO"),
    # O
    "oman": ("en", "OM"),
    # P
    "pakistan": ("en", "PK"),
    "palau": ("en", "PW"),
    "palestine": ("en", "PS"),
    "panama": ("en", "PA"),
    "papua new guinea": ("en", "PG"),
    "paraguay": ("en", "PY"),
    "peru": ("en", "PE"),
    "philippines": ("en", "PH"),
    "poland": ("en", "PL"),
    "portugal": ("en", "PT"),
    # Q
    "qatar": ("en", "QA"),
    # R
    "romania": ("en", "RO"),
    "russia": ("en", "RU"),
    "rwanda": ("en", "RW"),
    # S
    "saint kitts and nevis": ("en", "KN"),
    "saint lucia": ("en", "LC"),
    "saint vincent and the grenadines": ("en", "VC"),
    "samoa": ("en", "WS"),
    "san marino": ("en", "SM"),
    "sao tome and principe": ("en", "ST"),
    "saudi arabia": ("en", "SA"),
    "senegal": ("en", "SN"),
    "serbia": ("en", "RS"),
    "seychelles": ("en", "SC"),
    "sierra leone": ("en", "SL"),
    "singapore": ("en", "SG"),
    "slovakia": ("en", "SK"),
    "slovenia": ("en", "SI"),
    "solomon islands": ("en", "SB"),
    "somalia": ("en", "SO"),
    "south africa": ("en", "ZA"),
    "south korea": ("en", "KR"),
    "south sudan": ("en", "SS"),
    "spain": ("en", "ES"),
    "sri lanka": ("en", "LK"),
    "sudan": ("en", "SD"),
    "suriname": ("en", "SR"),
    "sweden": ("en", "SE"),
    "switzerland": ("en", "CH"),
    "syria": ("en", "SY"),
    # T
    "taiwan": ("en", "TW"),
    "tajikistan": ("en", "TJ"),
    "tanzania": ("en", "TZ"),
    "thailand": ("en", "TH"),
    "timor-leste": ("en", "TL"),
    "togo": ("en", "TG"),
    "tonga": ("en", "TO"),
    "trinidad and tobago": ("en", "TT"),
    "tunisia": ("en", "TN"),
    "turkey": ("en", "TR"),
    "turkmenistan": ("en", "TM"),
    "tuvalu": ("en", "TV"),
    # U
    "uganda": ("en", "UG"),
    "ukraine": ("en", "UA"),
    "united arab emirates": ("en", "AE"),
    "uae": ("en", "AE"),
    "united kingdom": ("en", "GB"),
    "uk": ("en", "GB"),
    "united states": ("en", "US"),
    "usa": ("en", "US"),
    "america": ("en", "US"),
    "uruguay": ("en", "UY"),
    "uzbekistan": ("en", "UZ"),
    # V
    "vanuatu": ("en", "VU"),
    "vatican": ("en", "VA"),
    "venezuela": ("en", "VE"),
    "vietnam": ("en", "VN"),
    # Y
    "yemen": ("en", "YE"),
    # Z
    "zambia": ("en", "ZM"),
    "zimbabwe": ("en", "ZW"),
}
